### ISSUE TITLE
Hello World: FastAPI

### ISSUE THREAD

**Issue by srstone20** [COSC481W-2023Fall/SAIO#1]
# Set up a FastAPI backend.

### User Story

As a developer, I need to be able to execute all CRUD actions (Create, Read, Update, Delete). Setting up this backend API will allow the frontend to be able to communicate with the database.

### Tasks

- [ ] CRUD Action: Create
- [ ] CRUD Action: Read
- [ ] CRUD Action: Update
- [ ] CRUD Action: Delete
- [ ] Testing page: included in FastAPI located at url/docs

### Acceptance

1. All CRUD actions are functional
2. Testing page in `/docs` is able to perform all CRUD actions
