### ISSUE TITLE
✏⚛️ Navigation Bar

### ISSUE THREAD

**Issue by srstone20** [COSC481W-2023Fall/SAIO#10]
## User Story

As a user, I want to be able to move between apps without going to the home page by using a navigation bar. Don't worry about styling too much at this point in time.

## Tasks

- [x] Creating a navigation bar on the side or top for easier movement with buttons for each main app (home, flashcards, calendar, todo)
- [x] Add option to open and close the bar
- [x] Placeholder icons / functionality for each button

## Acceptance Criteria:

- [ ] A segment for each app on the bar.
- [ ] being able to hide the bar on the side.
- [ ] each app is easily distinguishable.
