### ISSUE TITLE
✏⚛️ ☑  Create To-Do List Task

### ISSUE THREAD

**Issue by srstone20** [COSC481W-2023Fall/SAIO#11]
## User Story

As a user, I want to add tasks to my to-do list and need a GUI system to do so and have them be saved to my account.

## Tasks

- [x] Create a React component for the To-Do Task
- [x] Create a React component to contain the to-do tasks with the functionality to display all the tasks and add new ones
- [x] Upon a CRUD action for a task, send an appropriate request to the backend
- [x] Put due dates each todo task

## Acceptance

- [x] User can add new tasks
- [x] User can modify tasks
- [x] User can delete tasks
- [x] All tasks are displayed on the todo list for the user to see and interact
