### ISSUE TITLE
✏👨 Account Login Page

### ISSUE THREAD

**Issue by srstone20** [COSC481W-2023Fall/SAIO#12]
## User Story

As a user, I want to be able to log into my previously created account. To log in, I need to enter my username and password. Upon login, I now have access to the apps (home, to-do, etc) and my data. 

## Tasks

- [x] Create a login page
- [x] Send requests to the database for logging in
- [x] Message for invalid login
- [x] Store login information client-side so that the requests have correct information when using the apps

## Acceptance

- [x] The backend should check that the login credentials are valid
- [x] If invalid, then a proper message should be sent back. Else do nothing (for now)
