### ISSUE TITLE
✏🎨 Account Creation Page

### ISSUE THREAD

**Issue by srstone20** [COSC481W-2023Fall/SAIO#14]
## User Story

As a user, I want to be able to join SAIO's amazing community and use their awesome web apps! To do this, I need to create an account.

## Tasks

- [x] Create a React component representing the create account page (form) at the url `/account`
- [x] Send a POST request to the backend `/account`
- [x] Verify on the backend that the account can be made (no duplicate emails)
- [x] Add account to database with defaul values
- [x] Add a MongoDB collection to hold the account information

## Acceptance

- [x] The user can navigate to the account page
- [x] The user can create an account given the information is valid

**Comment by ayobamiseun** [comment]
can i be part of this i am a frontend developer React.

**Comment by srstone20** [comment]
@ayobamiseun Hello thanks for asking! This is a school project, so we can't have any outside help. We appreciate the interest!
