### ISSUE TITLE
✏🏃 Hello World: FastAPI

### ISSUE THREAD

**Issue by srstone20** [COSC481W-2023Fall/SAIO#2]
# Set up a FastAPI backend.

### User Story

As a developer, I need to execute all CRUD actions (Create, Read, Update, Delete) on a testing endpoint with the path `/test` to make sure the backend is working. Setting up this backend API will allow the frontend to be able to communicate with the database. If the real MongoDB connection string isn't available, use a fake one.

### Tasks

- [ ] Create endpoint: `(POST) /test` for creating test data
- [ ] Create endpoint: `(GET) /test` for reading test data
- [ ] Create endpoint: `(PATCH) /test` for updating test data
- [ ] Create endpoint: `(DELETE) /test` for deleting test data
- [ ] Connect o the real MongoDB once a connection string is provided

### Acceptance
- [ ] All CRUD actions are functional
- [ ] Testing page in `/docs` is able to perform all CRUD actions
