### ISSUE TITLE
🛠 Fix CORS and DB Connection

### ISSUE THREAD

**Issue by srstone20** [COSC481W-2023Fall/SAIO#27]
**User Story**
As a user, I want my information to be saved to a database so I can access my data on different machines
- Persona:A user with multiple machines with the same account
- Feature:A frontend application that connects to the backend server
- Business Value: Users will be able to come back to the app and have their data saved

**Tasks**
- [x] Fix database connection on deployed version
- [x] add link to CORS middleware to allow frontend - backend communication

**Acceptance**
- [x] the deployed app has access to the database 
- [x] the frontend server is not blocked from making requests to backend

**Comment by srstone20** [comment]
This issue doesn't really have a branch since we were just trying to get this issue resolved as fast possible. The changes for this were pushed directly to main. Sorry for the messiness and bad practice.
