### ISSUE TITLE
🏃🍃 Connect Todo to Mongo

### ISSUE THREAD

**Issue by srstone20** [COSC481W-2023Fall/SAIO#28]
**User Story**
As a user I want to save my todo items in the MongoDB so that I can access them whenever I log into my account, even across different machines.
- **Persona:** A user who uses the app across different machines
- **Feature:** Saving todos to your account
- **Business Value:** Users have more flexibility when working with SAIO

**Tasks**
- [x] Create a MongoDB collection for todo tasks.
  - [x] Schema should include email, task name, didComplete, and task id
- [x] Create the backend API endpoint for todo
 - [x] create - accept a email and task info, create a todo task
 - [x] read - accept an email and return all tasks
 - [x] update - changed the name of a task given the id
 - [x] delete - remove the task from the collection
- [x] Connect frontend to backend

**Acceptance**
- [x] A MongoDB for todo tasks exists
- [x] From the backend /docs pages, I am able to do all CRUD on a test account
- [x] From the frontend page, I can do all the CRUD
