### ISSUE TITLE
📆 ⚛️ Calendar App: Frontend

### ISSUE THREAD

**Issue by srstone20** [COSC481W-2023Fall/SAIO#29]
**User Story**
As a user I want to have a calendar app so that I can keep track of upcoming events, dates, and the such.
- **Persona:** A user who wants to manage their time with a calendar
- **Feature:** A front end calendar which can display more detailed information about each day (events)
- **Business Value:** Having a calendar app will allow users to better manage their time with SAIO

**Tasks**
- [ ] Create the calendar component using a calendar module import (react-big-calendar)
- [ ] Create a form for adding new events to the calendar. Each event has:
    - [ ] ID
    - [ ] Title
    - [ ] Start DateTime
    - [ ] End DateTime
    - [ ] Category
- [ ] New Events are sent to the backend for processing

**Acceptance**
- [ ] I can see a calendar when navigating to /app/calendar
- [ ] I can add events to the calendar on the correct days
- [ ] I can have event titles and categories
- [ ] New events are sent to the backend
