### ISSUE TITLE
✏🥬 Hello World: MongoDB

### ISSUE THREAD

**Issue by srstone20** [COSC481W-2023Fall/SAIO#3]
# Set up a Mongo Database

### User Story

As a developer, I need a database for storing data objects. MongoDB has CRUD actions built in.

### Tasks

- [x] Create Mongo database with your personal account
- [x] Create Mongo collection called "test" which will contain the testing data

### Acceptance

- [x] A MongoDB instance has been created with the "test" collection in it
