### ISSUE TITLE
📆 🍃 Calendar App: Backend FastAPI

### ISSUE THREAD

**Issue by srstone20** [COSC481W-2023Fall/SAIO#30]
**User Story**
As a user I want to be able to have all of my events in one database for querying and viewing
- **Persona:** A user who wants to manage their calendar by adding events to a database
- **Feature:** A backend calendar which can store more detailed information about each day (events)
- **Business Value:** Having a calendar app will allow users to better manage their time with SAIO

**Tasks**
- [ ] Create a model for calendar events
    - The model will be used for receiving json data from the frontend and for sending objects to the database
- [ ] The model will have the following variables
    - [ ] ID
    - [ ] Title
    - [ ] Start DateTime
    - [ ] End DateTime
    - [ ] Category
- [ ] Create database functions to execute the CRUD actions
    - [ ] CREATE
    - [ ] READ
    - [ ] UPDATE
    - [ ] DELETE
- [ ] Create the route methods for FastAPI to process requests and responses

**Acceptance**
- [ ] The database is able to send and receive data
- [ ] The db functions are able to perform the CRUD actions
- [ ] The routing methods call the right db function
- [ ] The routes send and receive responses and requests
