### ISSUE TITLE
📆 ⚛️ Calendar App: Bonus Features

### ISSUE THREAD

**Issue by srstone20** [COSC481W-2023Fall/SAIO#31]
**These features would be nice to have for the Calendar, but need to be researched if they can be done this Sprint**

**User Story**
As a user I want to be able to filter which events show up on the calendar and have a more detailed "Next Task" section
- **Persona:** A user who wants to filter the events shown on the calendar and their next teasks
- **Feature:** Filter check boxes which can show or hide certain events by category
- **Feature:** A sidebar window that shows the next events on the calendar
- **Business Value:** Being able to filter events will make it easier to view events if the calendar has a lot of items
- **Business Value:** Having a Next Task section will make it clear what's coming next

**Tasks**
- [ ] Create a checkbox menu for filtering events
- [ ] Create a side menu that shows upcoming tasks

**Acceptance**
- [ ] Calendar hides or shows events based on the check boxes selected
- [ ] Side menu shows the tasks that are coming up next
