### ISSUE TITLE
✏⚛️Create Frontend for Notes

### ISSUE THREAD

**Issue by srstone20** [COSC481W-2023Fall/SAIO#33]
**User Story**
As a user I want to have a notes app so that I can take notes for any reason within the same environment as the other apps.
- **Persona:** A user who needs to take notes
- **Feature:** A frontend page(s) for creating and editing notes
- **Business Value:** Having a notes app will be a primary feature of SAIO and provide great value to users

**Tasks**
- [x] Research how the Notes could be done. Refer to the balsamiq wireframe for general look reference
- [x] The page /app/notes will allow the user to create a new book or click on an old one and navigate to it
- [x] Create a component representing the book. When clicked, this will take you to the book. These are on the /app/notes page
- [ ] Create a component representing a section of the notebook
- [x] Create a component for displaying the contents of a notebook section
  - [x] Able to update the text in the notebook

**Acceptance**
- [ ] The page /app/notes contains a list of all the user's notes
- [ ] Can create a new notebook
- [ ] Can open a notebook and get routed to /app/notes/{book-id}
- [ ] Can open a section of the book which gets routed to /app/notes/{book-id}/{section-id}
- [ ] Can edit and view a notebook section.
