### ISSUE TITLE
✏🍃🏃 Create backend for Notes

### ISSUE THREAD

**Issue by srstone20** [COSC481W-2023Fall/SAIO#34]
**User Story**
As a user I want to have my notes be stored in the backend so that I don't have to worry about them being lost and can access my notes anywhere upon signing in.
- **Persona**: A user who wants to save their notes to their account
- **Feature**: Saving notes to the database and accessing through the backend
- **Business Value**: Having the ability to save notes to my account increases user satisfaction and trust for SAIO

**Tasks**
- [x] Create a DB collection for notebooks
- [x] Create an API endpoint for **NOTEBOOKS**
   - [x] create: (POST) /notes/book - create a new notebook
   - [x] read: (GET) /notes/book - get all of the user's notes
   - [x] update: (PUT) /notes/book - update a notes name
   - [x] delete: (DELETE) /notes/book- delete a notebook

**Acceptance**
- [ ] A database collection has been made
- [ ] All CRUD actions for notebooks are working with test account in the backend /docs pages
