### ISSUE TITLE
Restructuring folder organization for consistent code

### ISSUE THREAD

**Issue by srstone20** [COSC481W-2023Fall/SAIO#41]
# User Story
As a developer I want to have the backend and frontend folder structure be organized and consistent so I can easily create new features and understand what peers have made.
- Persona: A developer that wants to have an easy to work with codebase
- Feature: Organized and consistent file structure
- Business Value: Having a good organization decreases time to create new features
- [Google Doc with the Folder Structure Layout](https://docs.google.com/document/d/1V6PhgLaNI59LXJL13enqBse5s1RWlI-PQOXMpsUaaFA/edit)

# Tasks
- [x] Organize frontend by moving pages to the "pages" folder
- [x] Organize backend by moving endpoints into the "paths" folder, each in their own .py file

# Acceptance
- [x] Each backend path has its own file and the URL path matching folder path
- [x] All pages are in the pages folder for frontend

# Note 
This is assigned to everyone because we all were together and fixed it

**Comment by srstone20** [comment]
Here is a discussion about fixes we can try:

https://github.com/tiangolo/fastapi/issues/1663
