### ISSUE TITLE
✏ ⚛️ 🔗 Hello World: Connect React to Backend

### ISSUE THREAD

**Issue by srstone20** [COSC481W-2023Fall/SAIO#5]
## User Story

As a developer, I want to interact with test data from the backend in order to provide interactive apps in the future.

## Tasks
- [ ] Retrieve and display data from backend `(GET) /test` endpoint
- [ ] Send data to the backend using `(POST) /test` endpoint
- [ ] Update test data by using the `(PATCH) /test` endpoint
- [ ] Delete data from the backend using `(DELETE) /test`

## Acceptance
- [ ] I can get all of the test data from the backend and display it on the HTML page
- [ ] I can add new data to the backend
- [ ] I can update data in the backend (replace old with new)
- [ ] I can delete data from the backend
