### ISSUE TITLE
💸🧑‍🦲Account Functionality - Tokens

### ISSUE THREAD

**Issue by srstone20** [COSC481W-2023Fall/SAIO#56]
# User Story
As a user, I want the frontend to remember my login credentials so I can use SAIO's authorized features which include every applet.
- Persona: A user that wants to use SAIO
- Feature: The backend creates a token for the frontend, he frontend gives the token wherever it is needed
- Business Value: Allowing using to use SAIO with their own account is important for security and  personalization

#Tasks
- [x] Generate a token serverside using timestamp and user information (like Account ObjectId, name, whatever) upon login
- [x] Send the token upon login / signup and store it client side
- [x] Send the token back to the server for any feature which requires the user to be logged
- [x] For authorized features where a token isn't provided, redirect to login page
- [x] If the token is invalid, redirect to login

#Acceptance
- [x] The server sends back a token upon login or signup
- [x] The user cannot access authorized features without logging in first instead being redirected
- [x] The user can access authorized features once they have logged in and received the token
- [x] Functionality of features isn't altered
