### ISSUE TITLE
🌤🌔 Light and Dark Mode

### ISSUE THREAD

**Issue by srstone20** [COSC481W-2023Fall/SAIO#57]
# User Story
As a user I want to have light and dark mode themes so I can prevent my eyes from straining
- Persona: A user that wants to use have light/dark modes
- Feature: The user can choose between light and dark themes
- Business Value: Having a light and dark theme will provide user satisfaction

# Tasks
- [ ] Create a way to switch between different themes (not just light and dark, more themes are coming later)
    - [ ] Research how this could be done in React
- [ ] Create the styling for standard light theme
- [ ] Create the styling for standard dark theme

Acceptance
- [ ] I can switch between light and dark themes
