### ISSUE TITLE
✨Site-wide styling Revamp

### ISSUE THREAD

**Issue by srstone20** [COSC481W-2023Fall/SAIO#58]
# User Story
As a user I want to have a flashcard app so that I use flashcards to study for different subjects.
- Persona: A user that wants their eyes to not burn when using our site
- Feature: Updated and consistent position and sizing styling (color will come later)
- Business Value: Having a pleasant UI increases user enjoyment

# Tasks
- [x] Fix flickering when navigating between pages
- [x] Home page has placeholder divs and text (under construction)
- [ ] Update the Todo position and sizing styles
- [ ] Update the Flashcards position and sizing styles
- [ ] Update the Calendar position and sizing style
- [ ] Update the Notes position and sizing styles
- [x] Sidebar is properly sized between every page

Acceptance
- [x] The home applet has content which signifies it's in progess
- [ ] Every other applet has pleasing and consistent styling

**Comment by srstone20** [comment]
I didn't get the chance to style all of the apps consistently, it took a lot longer than expected to get the sidebar working correctly
