### ISSUE TITLE
📆 ⚛️ Calendar App - Individual Users

### ISSUE THREAD

**Issue by srstone20** [COSC481W-2023Fall/SAIO#59]
**User Story**
As a user I want to be able to see just my events as well as generic common events such as holidays.
- **Persona:** A user who wants to manage their calendar individually
- **Feature:** A backend calendar which can store events based on logged in user
- **Business Value:** Having a calendar app will allow users to better manage their time with SAIO

**Tasks**
- [ ] Change the backend to include either User Email or User ID in the calendar events
    - The model and database function would have to be updated
- [ ] Change the frontend so that only the logged in user's events render
- [ ] Add Holiday events to the database

**Acceptance**
- [ ] The calendar only renders the logged in user events
- [ ] The holidays render regardless of an user being logged in

**Timeline**
- Done by 19 November 2023
