### ISSUE TITLE
✏🐬 Deploy to DigitalOcean

### ISSUE THREAD

**Issue by srstone20** [COSC481W-2023Fall/SAIO#6]
# Deploying Project to DigitalOcean

### User Story

As a development team, we need the project functional on Digital Ocean. Once the project is hosted, any pushes to the main branch of the GitHub Repository will automatically update the Digital Ocean project

### Tasks

- [x] Create account for the primary account holder
- [x] Create Project
- [x] Create TWO Applets (one for front end, one for backend) on the App Platform, following the prompts
- [x] Add Database connection to secret variable for the backend
- [x] Add Procfile to the backend. Frontend should just work, but add Procfile if you need

### Acceptance

- [ ] The frontend is reachable through the applet's public URL and works as expected
- [ ] The backend is reachable through the applet's public URL (go to `/docs` for approval) and works as expected

**Comment by srstone20** [comment]
![image](https://github.com/COSC481W-2023Fall/SAIO/assets/89815932/997088f7-3ad1-4af8-8cbf-868d89e9fd86)

**Comment by srstone20** [comment]
![image](https://github.com/COSC481W-2023Fall/SAIO/assets/89815932/ea5df82e-f6da-44ce-9e3f-7f50b5b11c13)
