### ISSUE TITLE
Beta Test - Deren - Calendar Updates

### ISSUE THREAD

**Issue by DerenB** [COSC481W-2023Fall/SAIO#72]
# User Story

The user that tested the Calendar App made comments on what could be improved.
- Persona: A user wants more clear instructions on how to use the Calendar
- Feature: The user has an easier time navigating the App
- Business Value: Users don't want to spend time trying to learn an App. An App that is easier to learn will retain more users.

# Tasks

- [ ] Create a Title at the top of the page so Users know what page they're on.
- [ ] Add instructions at the top of the page describing what can be done.
- [ ] Add instructions in the forms that open when the buttons are clicked.
- [ ] Add a subtitle under the Event List that describes the Event List.

# Acceptance

- [ ] There is a title on the page
- [ ] There are instructions on how to use the page
- [ ] There are instructions on the forms when the buttons are clicked 
- [ ] There is a subtitle under the Event List
