### ISSUE TITLE
Beta Test - Flashcards UI

### ISSUE THREAD

**Issue by rliu13** [COSC481W-2023Fall/SAIO#73]
# User Story

As a user I want to be navigate seamlessly between viewing and managing my flashcards.
- Persona: A user that wants to use the flashcards feature.
- Feature: The user will be prompted to head to the manage flashcards page if they currently do not have any flashcards sets. If they do have flashcard sets created, they will be displayed on the page and not hidden within a drop down list.
- Business Value: New users will have a better experience if it is the first time they are using the flashcards app and existing users will be provided with a better UI experience.
 
# Tasks

- [ ] Display a prompt to the users that they have to create categories and flashcards if they currently have none created 
- [ ] Display categories on the display flashcards page as clickable buttons instead of a drop down list 

# Acceptance

- [ ] Users are displayed a prompt with a link to the manage flashcards page notifying them to create flashcards if they have none created yet
- [ ] Users can click on the categories they have created on the display flashcards page to show the entire flashcard set
