### ISSUE TITLE
🏡Home Page

### ISSUE THREAD

**Issue by srstone20** [COSC481W-2023Fall/SAIO#74]
# User Story
 
As a user, I want all of SAIO's features summarized in one place so that I can get a good overview of what I need to do today!
- Persona: A user who wants to have everything on one page
- Feature: Home page pulls information from todo, calendar, and flashcards
- Business Value: Having everything on one page increases flexibility and therefore users can use the app how they want

# Tasks: 

- [ ] Create a React element to contain today's work
- [ ] Create (or maybe reuse) a react element for todos that are not completed
    - [ ] They can be edited, crossed out, and deleted like regular todos 
- [ ] Create a react element which contains random flashcards.
    - [ ] The flashcards function the exact same as flashcards in the flashcards app
    - [ ] Add a feature to remove the flashcard review container
- [ ] The today's work container should be able to contain both of the above and they should function as expected.
- [ ] Flashcards periodically appear in today's work so the user is reminded to review them

# Acceptance criteria:

- [ ] The home page is no longer "under construction" and has the today's work section.
- [ ] The today's work page pulls data from the appropriate sources (flashcards, todos)
- [ ] The user can regularly interact with todos and flashcards.
