### ISSUE TITLE
Beta Test - Todo Updates

### ISSUE THREAD

**Issue by srstone20** [COSC481W-2023Fall/SAIO#78]
# User Story

As a user I wanted to add a date to the task I created to know when I need it completed by.

- Persona: User wants to creates date for the task to be completed by.
- Future: With the date users are able to keep on track with the tasks and knows what's needed done at what time.
- business: With the date users is able to get more work done and complete the tasks on time making more time for other things.

# Tasks

- [ ] A date is created along with each task
- [ ] Displays the date of the task along with the task itself
- [ ] The Date is stored along with the rest of the task.

# Acceptance

- [ ] User is able to add a date to the task they created.
- [ ] User is able to see the date of the task with the task.
- [ ] User is able to edit the date of the task.
- [ ] The date of the task is stored in the database

# Report
https://docs.google.com/document/d/1gQ4UU2lSWQTwjbGKQ8emOZ3tgtaJ7p-C/edit?usp=sharing&ouid=109102754765090494113&rtpof=true&sd=true

After the tester finish with the app he talked about wanting to add dates to the task so he can keep better track of them.
