### ISSUE TITLE
🐑 Custom Style - Sam

### ISSUE THREAD

**Issue by srstone20** [COSC481W-2023Fall/SAIO#80]
# User Story
As a user, I want more themes to choose the one I like best
- **Persona**: A user who wants to be able to select from many themes
- **Feature**: Styling for the new theme
- **Business Value**: Having many themes means more users can find a look that works for them

# Tasks
- [ ] Add new theme(s) of your liking
- [ ] The name of the theme matches how it looks

# Acceptance
- [ ] There are X many new themes with appropriate names

# Report

https://docs.google.com/document/d/1ELkm5PxtQmpyegup5RnBSJxcXC7k57R0HetVxyVNFlg/edit

> The styling made it hard to read
