### ISSUE TITLE
Bete Test -  Link Notes and Calendar To Account

### ISSUE THREAD

**Issue by srstone20** [COSC481W-2023Fall/SAIO#81]
# User Story

The user who tested the App made comments on what could be improved.
- Persona: A user wants their notes and calendar events tied to their own account
- Feature: The user will have saved data 
- Business Value: Users will be encouraged to come back to the app because their data is saved 

 Reference to beta Testing https://docs.google.com/document/d/1dJdsGGorEY4Goj5ez1L_VH2q02loehUzxYd-BzxJF-c/edit

![Image](https://github.com/COSC481W-2023Fall/SAIO/assets/122895883/001ecaf3-3633-4efa-b3ff-1218f1f79354)

# Tasks

- [ ] Change the backend of the calendar app 
- [ ] change backend of note app 

# Acceptance

- [ ] Calendar events are saved and tied to the user
- [ ] Notes are saved and tied to the user
