### ISSUE TITLE
Bete Test - Account Page

### ISSUE THREAD

**Issue by srstone20** [COSC481W-2023Fall/SAIO#82]
# User Story

The user who tested the App made comments on what could be improved.
- Persona: A user wants to see their account information and be able to access edit account page
- Feature: The user can view their account information and link it to edit account page
- Business Value: Gives users the flexibility to edit their account from the app and view their information if they forgot it.

Reference to beta testing https://docs.google.com/document/d/1dJdsGGorEY4Goj5ez1L_VH2q02loehUzxYd-BzxJF-c/edit

![Image](https://github.com/COSC481W-2023Fall/SAIO/assets/122895883/c367cf7d-740d-4e88-937f-7a6358ea0fe7)

# Tasks

- [ ]  Create account information page 
- [ ] Link This page to edit account Page 
- [ ] Link the account page  on the main app 

# Acceptance

- [ ] Account page shows the correct information
- [ ] Routes work as intended
